INSERT INTO inputs (id,description, input_number) VALUES ('1','Alimento para personas', '211')
INSERT INTO inputs (id,description, input_number) VALUES ('2','Alimento para animales', '212')
INSERT INTO inputs (id,description, input_number) VALUES ('3', 'Productos pecuarios', '213')
INSERT INTO inputs (id,description, input_number) VALUES ('4', 'Productos agroforestales', '214')
INSERT INTO inputs (id,description, input_number) VALUES ('5', 'Madera ,corcho y sus manufacturas', '215')
INSERT INTO inputs (id,description, input_number) VALUES ('6', 'Otros', '219')
INSERT INTO inputs (id,description, input_number) VALUES ('7', 'Hilados y Tela', '221')
INSERT INTO inputs (id,description, input_number) VALUES ('8', 'Prendas de Vestir', '222')
INSERT INTO inputs (id,description, input_number) VALUES ('9', 'Confecciones Textiles','223')